const CITY_TO_REGION: Record<string, string> = {
  // Île-de-France
  paris: 'Île-de-France',
  versailles: 'Île-de-France',
  'boulogne-billancourt': 'Île-de-France',
  'neuilly-sur-seine': 'Île-de-France',
  'issy-les-moulineaux': 'Île-de-France',
  'levallois-perret': 'Île-de-France',
  cergy: 'Île-de-France',
  évry: 'Île-de-France',
  evry: 'Île-de-France',
  massy: 'Île-de-France',
  palaiseau: 'Île-de-France',
  saclay: 'Île-de-France',
  'saint-denis': 'Île-de-France',
  montreuil: 'Île-de-France',
  vincennes: 'Île-de-France',
  créteil: 'Île-de-France',
  creteil: 'Île-de-France',
  nanterre: 'Île-de-France',
  'rueil-malmaison': 'Île-de-France',
  suresnes: 'Île-de-France',
  puteaux: 'Île-de-France',
  courbevoie: 'Île-de-France',
  clamart: 'Île-de-France',
  'vélizy-villacoublay': 'Île-de-France',
  'velizy-villacoublay': 'Île-de-France',
  vélizy: 'Île-de-France',
  velizy: 'Île-de-France',
  meudon: 'Île-de-France',
  'gif-sur-yvette': 'Île-de-France',
  orsay: 'Île-de-France',
  'les ulis': 'Île-de-France',
  antony: 'Île-de-France',
  montrouge: 'Île-de-France',
  arcueil: 'Île-de-France',
  cachan: 'Île-de-France',
  'la défense': 'Île-de-France',
  'la defense': 'Île-de-France',
  châtillon: 'Île-de-France',
  chatillon: 'Île-de-France',
  malakoff: 'Île-de-France',
  'fontenay-sous-bois': 'Île-de-France',

  // Auvergne-Rhône-Alpes
  lyon: 'Auvergne-Rhône-Alpes',
  grenoble: 'Auvergne-Rhône-Alpes',
  'clermont-ferrand': 'Auvergne-Rhône-Alpes',
  'saint-étienne': 'Auvergne-Rhône-Alpes',
  'saint-etienne': 'Auvergne-Rhône-Alpes',
  annecy: 'Auvergne-Rhône-Alpes',
  chambéry: 'Auvergne-Rhône-Alpes',
  chambery: 'Auvergne-Rhône-Alpes',
  valence: 'Auvergne-Rhône-Alpes',
  villeurbanne: 'Auvergne-Rhône-Alpes',
  'caluire-et-cuire': 'Auvergne-Rhône-Alpes',
  bron: 'Auvergne-Rhône-Alpes',
  vénissieux: 'Auvergne-Rhône-Alpes',
  venissieux: 'Auvergne-Rhône-Alpes',
  meylan: 'Auvergne-Rhône-Alpes',
  crolles: 'Auvergne-Rhône-Alpes',
  échirolles: 'Auvergne-Rhône-Alpes',
  echirolles: 'Auvergne-Rhône-Alpes',
  montbonnot: 'Auvergne-Rhône-Alpes',

  // Hauts-de-France
  lille: 'Hauts-de-France',
  amiens: 'Hauts-de-France',
  roubaix: 'Hauts-de-France',
  tourcoing: 'Hauts-de-France',
  dunkerque: 'Hauts-de-France',
  valenciennes: 'Hauts-de-France',
  lens: 'Hauts-de-France',
  arras: 'Hauts-de-France',
  béthune: 'Hauts-de-France',
  bethune: 'Hauts-de-France',
  "villeneuve-d'ascq": 'Hauts-de-France',
  calais: 'Hauts-de-France',
  'boulogne-sur-mer': 'Hauts-de-France',
  'saint-quentin': 'Hauts-de-France',
  compiègne: 'Hauts-de-France',
  compiegne: 'Hauts-de-France',

  // Nouvelle-Aquitaine
  bordeaux: 'Nouvelle-Aquitaine',
  pau: 'Nouvelle-Aquitaine',
  limoges: 'Nouvelle-Aquitaine',
  poitiers: 'Nouvelle-Aquitaine',
  'la rochelle': 'Nouvelle-Aquitaine',
  bayonne: 'Nouvelle-Aquitaine',
  angoulême: 'Nouvelle-Aquitaine',
  angouleme: 'Nouvelle-Aquitaine',
  mérignac: 'Nouvelle-Aquitaine',
  merignac: 'Nouvelle-Aquitaine',
  pessac: 'Nouvelle-Aquitaine',
  talence: 'Nouvelle-Aquitaine',
  biarritz: 'Nouvelle-Aquitaine',
  niort: 'Nouvelle-Aquitaine',
  périgueux: 'Nouvelle-Aquitaine',
  perigueux: 'Nouvelle-Aquitaine',
  agen: 'Nouvelle-Aquitaine',

  // Occitanie
  toulouse: 'Occitanie',
  montpellier: 'Occitanie',
  nîmes: 'Occitanie',
  nimes: 'Occitanie',
  perpignan: 'Occitanie',
  béziers: 'Occitanie',
  beziers: 'Occitanie',
  albi: 'Occitanie',
  castres: 'Occitanie',
  tarbes: 'Occitanie',
  narbonne: 'Occitanie',
  carcassonne: 'Occitanie',
  montauban: 'Occitanie',
  blagnac: 'Occitanie',
  labège: 'Occitanie',
  labege: 'Occitanie',

  // Grand Est
  strasbourg: 'Grand Est',
  reims: 'Grand Est',
  metz: 'Grand Est',
  nancy: 'Grand Est',
  mulhouse: 'Grand Est',
  colmar: 'Grand Est',
  épinal: 'Grand Est',
  epinal: 'Grand Est',
  troyes: 'Grand Est',
  'châlons-en-champagne': 'Grand Est',
  'chalons-en-champagne': 'Grand Est',
  thionville: 'Grand Est',

  // Provence-Alpes-Côte d'Azur
  marseille: "Provence-Alpes-Côte d'Azur",
  nice: "Provence-Alpes-Côte d'Azur",
  toulon: "Provence-Alpes-Côte d'Azur",
  'aix-en-provence': "Provence-Alpes-Côte d'Azur",
  avignon: "Provence-Alpes-Côte d'Azur",
  gap: "Provence-Alpes-Côte d'Azur",
  cannes: "Provence-Alpes-Côte d'Azur",
  antibes: "Provence-Alpes-Côte d'Azur",
  fréjus: "Provence-Alpes-Côte d'Azur",
  frejus: "Provence-Alpes-Côte d'Azur",
  aubagne: "Provence-Alpes-Côte d'Azur",
  'sophia antipolis': "Provence-Alpes-Côte d'Azur",
  valbonne: "Provence-Alpes-Côte d'Azur",
  mougins: "Provence-Alpes-Côte d'Azur",
  biot: "Provence-Alpes-Côte d'Azur",
  'la ciotat': "Provence-Alpes-Côte d'Azur",
  arles: "Provence-Alpes-Côte d'Azur",
  'salon-de-provence': "Provence-Alpes-Côte d'Azur",

  // Pays de la Loire
  nantes: 'Pays de la Loire',
  angers: 'Pays de la Loire',
  'le mans': 'Pays de la Loire',
  'saint-nazaire': 'Pays de la Loire',
  laval: 'Pays de la Loire',
  'la roche-sur-yon': 'Pays de la Loire',
  cholet: 'Pays de la Loire',

  // Normandie
  rouen: 'Normandie',
  caen: 'Normandie',
  'le havre': 'Normandie',
  cherbourg: 'Normandie',
  'cherbourg-en-cotentin': 'Normandie',
  évreux: 'Normandie',
  evreux: 'Normandie',
  alençon: 'Normandie',
  alencon: 'Normandie',

  // Bretagne
  rennes: 'Bretagne',
  brest: 'Bretagne',
  quimper: 'Bretagne',
  lorient: 'Bretagne',
  vannes: 'Bretagne',
  'saint-malo': 'Bretagne',
  'saint-brieuc': 'Bretagne',

  // Centre-Val de Loire
  orléans: 'Centre-Val de Loire',
  orleans: 'Centre-Val de Loire',
  tours: 'Centre-Val de Loire',
  chartres: 'Centre-Val de Loire',
  blois: 'Centre-Val de Loire',
  bourges: 'Centre-Val de Loire',
  châteauroux: 'Centre-Val de Loire',
  chateauroux: 'Centre-Val de Loire',

  // Bourgogne-Franche-Comté
  dijon: 'Bourgogne-Franche-Comté',
  besançon: 'Bourgogne-Franche-Comté',
  besancon: 'Bourgogne-Franche-Comté',
  belfort: 'Bourgogne-Franche-Comté',
  mâcon: 'Bourgogne-Franche-Comté',
  macon: 'Bourgogne-Franche-Comté',
  auxerre: 'Bourgogne-Franche-Comté',
  nevers: 'Bourgogne-Franche-Comté',
  'chalon-sur-saône': 'Bourgogne-Franche-Comté',
  'chalon-sur-saone': 'Bourgogne-Franche-Comté',

  // Corse
  ajaccio: 'Corse',
  bastia: 'Corse',
}

export const REGIONS: string[] = [
  'Auvergne-Rhône-Alpes',
  'Bourgogne-Franche-Comté',
  'Bretagne',
  'Centre-Val de Loire',
  'Corse',
  'Grand Est',
  'Hauts-de-France',
  'Île-de-France',
  'Normandie',
  'Nouvelle-Aquitaine',
  'Occitanie',
  'Pays de la Loire',
  "Provence-Alpes-Côte d'Azur",
]

export function cityToRegion(city: string | null): string | null {
  if (!city) return null
  const normalized = city.toLowerCase().trim()
  if (CITY_TO_REGION[normalized]) return CITY_TO_REGION[normalized]
  // Préfixe : "Paris 1er", "Lyon 3e", "Marseille 13"…
  for (const [key, region] of Object.entries(CITY_TO_REGION)) {
    if (normalized.startsWith(key + ' ') || normalized.startsWith(key + '-')) {
      return region
    }
  }
  return null
}
